### ISSUE TITLE
Error when autoModel load from pretrained

### ISSUE THREAD

**Issue by xiawei20161308104** [altndrr/vic#15]
![image](https://github.com/altndrr/vic/assets/39768827/305c2143-344d-420c-9373-39af195c3e79)
![image](https://github.com/altndrr/vic/assets/39768827/1ae4ad48-6f85-4b95-ba5c-919bbf2e664b)

Run according to the provided model card, and the error is as follows：
RuntimeError: Error in struct faiss::InvertedListsIOHook *__cdecl faiss::InvertedListsIOHook::lookup(int) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\invlists\InvertedListsIOHook.cpp:63: read_InvertedLists: could not load ArrayInvertedLists as 646f6c69 ("ilod")

**Comment by xiawei20161308104** [comment]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like altndrr/cased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by altndrr** [comment]
Thank you for taking interest in our work. The first issue (`RuntimeError: Error in struct faiss::InvertedListsIOHook *__cdecl faiss::InvertedListsIOHook::lookup(int) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\invlists\InvertedListsIOHook.cpp:63: read_InvertedLists: could not load ArrayInvertedLists as 646f6c69 ("ilod")`) simply means that faiss could not find the index to load.

The reason for this is probably due to Windows since I also managed to reproduce the problem on a Windows machine. Currently, I do not have a workaround for this on the OS, but it should be straightforward to debug and solve.

**Comment by altndrr** [comment]
I recently updated the model on HuggingFace, you can now specify a custom cache dir for your model with the code below:

```python
import requests
from PIL import Image
from transformers import AutoModel, AutoConfig, CLIPProcessor

# download an image from the internet
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

# load the model and the processor
config = AutoConfig.from_pretrained("altndrr/cased", trust_remote_code=True)
config.cache_dir = "./.cache"  # set you custom dir here
model = AutoModel.from_config(config, trust_remote_code=True)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14")

# get the model outputs
images = processor(images=[image], return_tensors="pt", padding=True)
outputs = model(images, alpha=0.7)
labels, scores = outputs["vocabularies"][0], outputs["scores"][0]

# print the top 5 most likely labels for the image
values, indices = scores.topk(3)
print("\nTop predictions:\n")
for value, index in zip(values, indices):
    print(f"{labels[index]:>16s}: {100 * value.item():.2f}%")
```

Let me know if you have any issue.
