### ISSUE TITLE
How to run cased by eval.py / train.py?

### ISSUE THREAD

**Issue by chenxinli001** [altndrr/vic#6]
May I know how to run cased by eval.py? I use the command like
` python src/eval.py experiment=method/cased.yaml`
While it returns the error as:
'requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /knn-service (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbafad40970>: Failed to establish a new connection: [Errno 111] Connection refused'))'

**Comment by altndrr** [comment]
Both CaSED and some baselines rely on a retrieval server, which we provide as a Docker container. To use it, please refer to the [Docker containers](https://github.com/altndrr/vic#docker-containers) section in the README of this repository. Upon starting the server for the first time, it should automatically download all the main faiss indices from Google Drive. However, I recently had some issues with downloading files via gdrive, and you may need to download some of the files manually.

Please let me know if you are able to successfully run our method. Also, thank you for bringing to my attention that this step was not clearly explained in the README. I will update it to ensure better clarity.

Edit: there was a typo in one of the Google Drive links (fixed in #7), now all the indices should download automatically.
